#!/bin/bash
echo "Starting Hourly cron" > /home1/sandiel8/www/live/cron/log
date >> /home1/sandiel8/www/live/cron/log

cd /home1/sandiel8/www/live/php/calledByCron
export GOOGLE_APPLICATION_CREDENTIALS='../netninja-game-guidez-1d8c2-firebase-adminsdk-w55cp-e90b7fc724.json'

# 30s sleeps, so 120 is 1HR
for i in {1..120}
do
    if (($i % 2 == 0 ))
    then
        echo "$i Keep WebSocket Running " >> /home1/sandiel8/www/live/cron/log
        ./KeepWebSocketRunning >> /home1/sandiel8/www/live/cron/log 
        # this is done on the Pi4 now because it ruqires gRPC to access users in firebase
        # echo "$i running TextChecker" >> /home1/sandiel8/www/live/cron/log
        # php TextChecker.php > checker.log 
        #!/usr/bin/env bash
    fi

    #cd /home/thillnea/www/gliderport/OpenWeather
    #php sync.php > sync.log
    
    #php UpdateCharts.php > charts.log
    #echo "$i running UpdateCharts" >> /home1/sandiel8/www/live/cron/log

    #Every 5 min
    if (($i % 10 == 0 ))
    then
        echo "$i running UpdateHistory" >> /home1/sandiel8/www/live/cron/log
        php UpdateHistory.php > history.log
    fi
    if [ $i -lt 120 ] 
    then
        sleep 30 
    else 
        echo "Do hourly things here" >> /home1/sandiel8/www/live/cron/log
        #php updateCodeDb.php 
    fi
done






#!/bin/bash
# make sure the background monitor is running
#monitorCron.pl >& monitorCron.errors
#cd /home1/sandiel8/www/live/php
 
 