#!/bin/bash
echo "Starting cron" > /home1/sandiel8/www/live/cron/log
date >> /home1/sandiel8/www/live/cron/log

cd /home1/sandiel8/www/live/php/calledByCron

t=4
while [ $t -lt 100 ]
do
    # 5 minutes is as fast as CRON will go so loop 5 times and sleep
    for i in {1..120}
    do
        #cd /home/thillnea/www/gliderport/OpenWeather
        #php sync.php > sync.log
        #export GOOGLE_APPLICATION_CREDENTIALS='netninja-game-guidez-1d8c2-firebase-adminsdk-w55cp-e90b7fc724.json'
        php UpdateCharts.php > charts.log
        echo "$i running UpdateCharts" >> /home1/sandiel8/www/live/cron/log
        if (($i % 10 == 0 ))
        then
            echo "$i running UpdateHistory" >> /home1/sandiel8/www/live/cron/log
            php UpdateHistory.php > history.log
        fi
        if [ $i -lt 120 ]
        then
            sleep 30
        else
            echo "Do hourly things here" >> /home1/sandiel8/www/live/cron/log
            #php updateCodeDb.php
        fi
    done
    sleep 60
done
