#!/usr/bin/env bash
cd ../phpWebSocketServer/server/
./keepServerRunning
exit 1

# if ! mkdir /tmp/keepsocketrunning_495867439573.lock; then
#     printf "Failed to acquire lock.\n" >&2
#     exit 1
# fi
# printf "File locked.\n" >&2
# cd /home1/sandiel8/www/live/php/
# #php webSocket.php
# trap 'rm -rf /tmp/keepsocketrunning_495867439573.lock' EXIT  # remove the lockdir on exit
